linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/costa92/go-protoc
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/costa92/go-protoc
          - github.com/gorilla/mux
          - github.com/grpc-ecosystem/grpc-gateway/v2
          - github.com/spf13/viper
          - github.com/spf13/pflag
          - go.uber.org/zap
          - google.golang.org/grpc
          - google.golang.org/protobuf
          - k8s.io/klog/v2
          - k8s.io/apimachinery
          - github.com/prometheus/client_golang
          - go.opentelemetry.io/otel
          - go.opentelemetry.io/contrib
          - github.com/go-playground/validator/v10
          - golang.org/x/time/rate
      tests:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/costa92/go-protoc
          - github.com/gorilla/mux
          - github.com/grpc-ecosystem/grpc-gateway/v2
          - google.golang.org/grpc
          - google.golang.org/protobuf

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
        - goconst
        - funlen
        - lll

  max-same-issues: 0
  max-issues-per-linter: 0

run:
  skip-dirs:
    - pkg/api
    - third_party
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.validate\\.go$"
    - ".*\\.pb\\.gw\\.go$"
  timeout: 5m