// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: pkg/api/helloworld/v1/helloworld.proto

package helloworldv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_pkg_api_helloworld_v1_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_helloworld_v1_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_pkg_api_helloworld_v1_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_helloworld_v1_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_pkg_api_helloworld_v1_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_api_helloworld_v1_helloworld_proto protoreflect.FileDescriptor

const file_pkg_api_helloworld_v1_helloworld_proto_rawDesc = "" +
	"\n" +
	"&pkg/api/helloworld/v1/helloworld.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc6\x01\n" +
	"\aGreeter\x12X\n" +
	"\bSayHello\x12\x1b.helloworld.v1.HelloRequest\x1a\x19.helloworld.v1.HelloReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/hello\x12a\n" +
	"\rSayHelloAgain\x12\x1b.helloworld.v1.HelloRequest\x1a\x19.helloworld.v1.HelloReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/hello/{name}BAZ?github.com/costa92/go-protoc/pkg/api/helloworld/v1;helloworldv1b\x06proto3"

var (
	file_pkg_api_helloworld_v1_helloworld_proto_rawDescOnce sync.Once
	file_pkg_api_helloworld_v1_helloworld_proto_rawDescData []byte
)

func file_pkg_api_helloworld_v1_helloworld_proto_rawDescGZIP() []byte {
	file_pkg_api_helloworld_v1_helloworld_proto_rawDescOnce.Do(func() {
		file_pkg_api_helloworld_v1_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_helloworld_v1_helloworld_proto_rawDesc), len(file_pkg_api_helloworld_v1_helloworld_proto_rawDesc)))
	})
	return file_pkg_api_helloworld_v1_helloworld_proto_rawDescData
}

var file_pkg_api_helloworld_v1_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_helloworld_v1_helloworld_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: helloworld.v1.HelloRequest
	(*HelloReply)(nil),   // 1: helloworld.v1.HelloReply
}
var file_pkg_api_helloworld_v1_helloworld_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Greeter.SayHello:input_type -> helloworld.v1.HelloRequest
	0, // 1: helloworld.v1.Greeter.SayHelloAgain:input_type -> helloworld.v1.HelloRequest
	1, // 2: helloworld.v1.Greeter.SayHello:output_type -> helloworld.v1.HelloReply
	1, // 3: helloworld.v1.Greeter.SayHelloAgain:output_type -> helloworld.v1.HelloReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_helloworld_v1_helloworld_proto_init() }
func file_pkg_api_helloworld_v1_helloworld_proto_init() {
	if File_pkg_api_helloworld_v1_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_helloworld_v1_helloworld_proto_rawDesc), len(file_pkg_api_helloworld_v1_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_helloworld_v1_helloworld_proto_goTypes,
		DependencyIndexes: file_pkg_api_helloworld_v1_helloworld_proto_depIdxs,
		MessageInfos:      file_pkg_api_helloworld_v1_helloworld_proto_msgTypes,
	}.Build()
	File_pkg_api_helloworld_v1_helloworld_proto = out.File
	file_pkg_api_helloworld_v1_helloworld_proto_goTypes = nil
	file_pkg_api_helloworld_v1_helloworld_proto_depIdxs = nil
}
