# 服务配置
# HTTP服务相关配置
http:
  # HTTP服务地址
  addr: ":8082"
    # 请求超时时间(秒)
  timeout: 5
  # gRPC服务相关配置
grpc:
    # gRPC服务地址
  addr: ":9093"
    # 服务关闭超时时间(秒)
  shutdown_timeout: 10


# 可观测性相关配置
# 链路追踪配置
tracing:
  # 服务名称
  service_name: "go-protoc-service"
  # 是否启用
  enabled: false
  # 导出器类型: stdout, jaeger, otlp
  exporter: "stdout"
  # 如果使用otlp导出器，指定其端点
  otlp_endpoint: "localhost:4317"

  # 指标监控配置
metrics:
  # 是否启用
  enabled: true
  # 指标路径
  path: "/metrics"


# 中间件配置
middleware:
  # 请求超时时间
  timeout: 30s

  # CORS跨域配置
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - HEAD
    allow_headers:
      - Authorization
      - Content-Type
      - X-Request-ID
      - X-Real-IP
    expose_headers: []
    allow_credentials: true
    max_age: 12h

  # 限流配置
  rate_limit:
    enable: true
    limit: 100
    burst: 200
    window: 1m

# 日志配置
log:
  # 日志级别: debug, info, warn, error, dpanic, panic, fatal
  level: "info"
  # 日志格式: console, json
  format: "console"
  # 是否开启调用者信息
  enable-caller: true
  # 日志输出路径: stdout, stderr, 或文件路径
  output-paths:
    - "stdout"
  # 错误日志输出路径
  error-output-paths:
    - "stderr"
