// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: errno/errno.proto

package errno

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 未知错误，服务器内部错误
	ErrorReason_Unknown ErrorReason = 0
	// 无效参数错误
	ErrorReason_InvalidParameter ErrorReason = 1
	// 未找到错误
	ErrorReason_NotFound ErrorReason = 2
	// 未经授权错误
	ErrorReason_Unauthorized ErrorReason = 3
	// 禁止访问错误
	ErrorReason_Forbidden ErrorReason = 4
	// 缺少幂等性令牌错误
	ErrorReason_IdempotentMissingToken ErrorReason = 5
	// 幂等性令牌已过期错误
	ErrorReason_IdempotentTokenExpired ErrorReason = 6
	// 请求路径没有找到
	ErrorReason_PageNotFound ErrorReason = 7
	// Gin 请求参数绑定失败
	ErrorReason_BindFailed ErrorReason = 8
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "Unknown",
		1: "InvalidParameter",
		2: "NotFound",
		3: "Unauthorized",
		4: "Forbidden",
		5: "IdempotentMissingToken",
		6: "IdempotentTokenExpired",
		7: "PageNotFound",
		8: "BindFailed",
	}
	ErrorReason_value = map[string]int32{
		"Unknown":                0,
		"InvalidParameter":       1,
		"NotFound":               2,
		"Unauthorized":           3,
		"Forbidden":              4,
		"IdempotentMissingToken": 5,
		"IdempotentTokenExpired": 6,
		"PageNotFound":           7,
		"BindFailed":             8,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_errno_errno_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_errno_errno_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_errno_errno_proto_rawDescGZIP(), []int{0}
}

var File_errno_errno_proto protoreflect.FileDescriptor

const file_errno_errno_proto_rawDesc = "" +
	"\n" +
	"\x11errno/errno.proto\x12\x05errno\x1a\x13errors/errors.proto*\xf5\x01\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUnknown\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x1a\n" +
	"\x10InvalidParameter\x10\x01\x1a\x04\xa8E\x90\x03\x12\x12\n" +
	"\bNotFound\x10\x02\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fUnauthorized\x10\x03\x1a\x04\xa8E\x91\x03\x12\x13\n" +
	"\tForbidden\x10\x04\x1a\x04\xa8E\x93\x03\x12 \n" +
	"\x16IdempotentMissingToken\x10\x05\x1a\x04\xa8E\x90\x03\x12 \n" +
	"\x16IdempotentTokenExpired\x10\x06\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fPageNotFound\x10\a\x1a\x04\xa8E\x94\x03\x12\x14\n" +
	"\n" +
	"BindFailed\x10\b\x1a\x04\xa8E\xf4\x03\x1a\x04\xa0E\xf4\x03B\x80\x01\n" +
	"\tcom.errnoB\n" +
	"ErrnoProtoP\x01Z3github.com/costa92/go-protoc/v2/pkg/api/errno;errno\xa2\x02\x03EXX\xaa\x02\x05Errno\xca\x02\x05Errno\xe2\x02\x11Errno\\GPBMetadata\xea\x02\x05Errnob\x06proto3"

var (
	file_errno_errno_proto_rawDescOnce sync.Once
	file_errno_errno_proto_rawDescData []byte
)

func file_errno_errno_proto_rawDescGZIP() []byte {
	file_errno_errno_proto_rawDescOnce.Do(func() {
		file_errno_errno_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errno_errno_proto_rawDesc), len(file_errno_errno_proto_rawDesc)))
	})
	return file_errno_errno_proto_rawDescData
}

var file_errno_errno_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errno_errno_proto_goTypes = []any{
	(ErrorReason)(0), // 0: errno.ErrorReason
}
var file_errno_errno_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errno_errno_proto_init() }
func file_errno_errno_proto_init() {
	if File_errno_errno_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errno_errno_proto_rawDesc), len(file_errno_errno_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errno_errno_proto_goTypes,
		DependencyIndexes: file_errno_errno_proto_depIdxs,
		EnumInfos:         file_errno_errno_proto_enumTypes,
	}.Build()
	File_errno_errno_proto = out.File
	file_errno_errno_proto_goTypes = nil
	file_errno_errno_proto_depIdxs = nil
}
