// Code generated by go generate; DO NOT EDIT.

package kratos

import (
	krtlog "github.com/go-kratos/kratos/v2/log"

	"github.com/costa92/go-protoc/v2/pkg/log"
)

func NewLogger(id, name, version string) krtlog.Logger {
	return krtlog.With(log.Default(),
		"ts", krtlog.DefaultTimestamp,
		"caller", krtlog.DefaultCaller,
		"service.id", id,
		"service.name", name,
		"service.version", version,
	)
}
