// Code generated by go generate; DO NOT EDIT.

package kratos

import (
	krtlog "github.com/go-kratos/kratos/v2/log"

	"github.com/onexstack/onexstack/pkg/log"
)

func NewLogger(id, name, version string) krtlog.Logger {
	return krtlog.With(log.Default(),
		"ts", krtlog.DefaultTimestamp,
		"caller", krtlog.DefaultCaller,
		"service.id", info.ID,
		"service.name", info.Name,
		"service.version", info.Version,
	)
}
