// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using GetUserRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetUserRequest) DeepCopyInto(out *GetUserRequest) {
	p := proto.Clone(in).(*GetUserRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetUserRequest. Required by controller-gen.
func (in *GetUserRequest) DeepCopy() *GetUserRequest {
	if in == nil {
		return nil
	}
	out := new(GetUserRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetUserRequest. Required by controller-gen.
func (in *GetUserRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetUserResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetUserResponse) DeepCopyInto(out *GetUserResponse) {
	p := proto.Clone(in).(*GetUserResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetUserResponse. Required by controller-gen.
func (in *GetUserResponse) DeepCopy() *GetUserResponse {
	if in == nil {
		return nil
	}
	out := new(GetUserResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetUserResponse. Required by controller-gen.
func (in *GetUserResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateUserRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateUserRequest) DeepCopyInto(out *CreateUserRequest) {
	p := proto.Clone(in).(*CreateUserRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateUserRequest. Required by controller-gen.
func (in *CreateUserRequest) DeepCopy() *CreateUserRequest {
	if in == nil {
		return nil
	}
	out := new(CreateUserRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateUserRequest. Required by controller-gen.
func (in *CreateUserRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateUserResponse within kubernetes types, where deepcopy-gen is used.
func (in *CreateUserResponse) DeepCopyInto(out *CreateUserResponse) {
	p := proto.Clone(in).(*CreateUserResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateUserResponse. Required by controller-gen.
func (in *CreateUserResponse) DeepCopy() *CreateUserResponse {
	if in == nil {
		return nil
	}
	out := new(CreateUserResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateUserResponse. Required by controller-gen.
func (in *CreateUserResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
